use bookfetch;

insert into user (first_name, last_name, email, address) values
("James", "Tremblay", "JamesTremblay@gmail.com", "1866 Second Drive, Baltimore"),
("Christopher", "Roy", "ChristopherRoy@gmail.com", "1131 Third Drive, Baltimore"),
("Ronald", "Gagnon", "RonaldGagnon@gmail.com", "9898 First Drive, Baltimore"),
("Mary", "Côté", "MaryCôté@gmail.com", "9190 Fourth Drive, Baltimore"),
("Lisa", "Bouchard", "LisaBouchard@gmail.com", "8926 Park Drive, Baltimore"),
("Michelle", "Gauthier", "MichelleGauthier@gmail.com", "8186 Fifth Drive, Baltimore"),
("John", "Morin", "JohnMorin@gmail.com", "7644 Main Drive, Baltimore"),
("Daniel", "Lavoie", "DanielLavoie@gmail.com", "7283 Sixth Drive, Baltimore"),
("Anthony", "Fortin", "AnthonyFortin@gmail.com", "6946 Oak Drive, Baltimore"),
("Patricia", "Gagné", "PatriciaGagné@gmail.com", "6377 Seventh Drive, Baltimore"),
("Nancy", "Martínez", "NancyMartínez@gmail.com", "6170 Pine Drive, Baltimore"),
("Laura", "García", "LauraGarcía@gmail.com", "6103 Maple Drive, Baltimore"),
("Robert", "Hernandez", "RobertHernandez@gmail.com", "5644 Cedar Drive, Baltimore"),
("Paul", "González", "PaulGonzález@gmail.com", "5524 Eighth Drive, Baltimore"),
("Kevin", "López", "KevinLópez@gmail.com", "5233 Elm Drive, Baltimore"),
("Linda", "Rodríguez", "LindaRodríguez@gmail.com", "5202 View Drive, Baltimore"),
("Karen", "Pérez", "KarenPérez@gmail.com", "4974 Washington Drive, Baltimore"),
("Sarah", "Sánchez", "SarahSánchez@gmail.com", "4908 Ninth Drive, Baltimore"),
("Michael", "Ramírez", "MichaelRamírez@gmail.com", "4901 Lake Drive, Baltimore"),
("Mark", "Flores", "MarkFlores@gmail.com", "4877 Hill Drive, Baltimore"),
("Mark", "Flores", "MarkFlores@gmail.com", "4877 Hill Drive, Baltimore"),
("Mark", "Flores", "MarkFlores@gmail.com", "4877 Hill Drive, Baltimore"),
("Michael", "Ramírez", "MichaelRamírez@gmail.com", "4901 Lake Drive, Baltimore"),
("Michael", "Ramírez", "MichaelRamírez@gmail.com", "4901 Lake Drive, Baltimore"),
("Michael", "Ramírez", "MichaelRamírez@gmail.com", "4901 Lake Drive, Baltimore"),
("Paul", "González", "PaulGonzález@gmail.com", "5524 Eighth Drive, Baltimore"),
("Paul", "González", "PaulGonzález@gmail.com", "5524 Eighth Drive, Baltimore"),
("Paul", "González", "PaulGonzález@gmail.com", "5524 Eighth Drive, Baltimore"),
("Paul", "González", "PaulGonzález@gmail.com", "5524 Eighth Drive, Baltimore"),
("Kevin", "López", "KevinLópez@gmail.com", "5233 Elm Drive, Baltimore"),
("Nancy", "Martínez", "NancyMartínez@gmail.com", "6170 Pine Drive, Baltimore"),
("Laura", "García", "LauraGarcía@gmail.com", "6103 Maple Drive, Baltimore"),
("Patricia", "Gagné", "PatriciaGagné@gmail.com", "6377 Seventh Drive, Baltimore"),
("Karen", "Pérez", "KarenPérez@gmail.com", "4974 Washington Drive, Baltimore"),
("Linda", "Rodríguez", "LindaRodríguez@gmail.com", "5202 View Drive, Baltimore"),
("Robert", "Hernandez", "RobertHernandez@gmail.com", "5644 Cedar Drive, Baltimore"),
("Robert", "Hernandez", "RobertHernandez@gmail.com", "5644 Cedar Drive, Baltimore"),
("Robert", "Hernandez", "RobertHernandez@gmail.com", "5644 Cedar Drive, Baltimore"),
("Robert", "Hernandez", "RobertHernandez@gmail.com", "5644 Cedar Drive, Baltimore"),
("Nancy", "Martínez", "NancyMartínez@gmail.com", "6170 Pine Drive, Baltimore"),
("John", "Morin", "JohnMorin@gmail.com", "7644 Main Drive, Baltimore"),
("", "", "", ""),
("", "", "", ""),
("", "", "", ""),
("Andrew", "Bower", "andrew.bower@bookfetchinc.com", "2312 M street, NW Suite 503"),
("Anne", "Stewart", "anne.stewart@bookfetchinc.com", "201 Hospital Drive"),
("Anthony", "Grant", "anthony.grant@bookfetchinc.com", "2315 M street, NW Suite 503"),
("Austin", "Morgan", "austin.morgan@bookfetchinc.com", "2223 Canterbury Drive"),
("Benjamin", "Vaughan", "benjamin.vaughan@bookfetchinc.com", "2550 Livingston Road"),
("Benjamin", "Dyer", "benjamin.dyer@bookfetchinc.com", "308 Langdon Street"),
("Boris", "McGrath", "boris.mcgrath@bookfetchinc.com", "2 West Lakeshore Drive"),
("Caroline", "Roberts", "caroline.roberts@bookfetchinc.com", "1001 East 100 North"),
("Connor", "Black", "connor.black@bookfetchinc.com", "305 Langdon Street"),
("Dan", "Martin", "dan.martin@bookfetchinc.com", "1 West Lakeshore Drive"),
("Dominic", "Lambert", "dominic.lambert@umbc.edu", "1000 Hilltop Cir, Baltimore, MD 21250"),
("Donna", "Scott", "donna.scott@bookfetchinc.com", "102 South 1st Street"),
("Heather", "Powell", "heather.powell@bookfetchinc.com", "2311 M street, NW Suite 503"),
("Jack", "Chapman", "jack.chapman@bookfetchinc.com", "104 South 1st Street"),
("Jack", "Allan", "jack.allan@bookfetchinc.com", "2221 Canterbury Drive"),
("James", "White", "james.white@bookfetchinc.com", "103 South 1st Street"),
("James", "Bell", "james.bell@bookfetchinc.com", "105 South 1st Street"),
("Joan", "Lawrence", "joan.lawrence@bookfetchinc.com", "2222 Canterbury Drive"),
("Joshua", "Vaughan", "joshua.vaughan@bookfetchinc.com", "2 West Lakeshore Drive"),
("Joshua", "Lee", "joshua.lee@bookfetchinc.com", "3 West Lakeshore Drive"),
("Julian", "Rees", "julian.rees@bookfetchinc.com", "600 Caisson Hill Road"),
("Karen", "Parsons", "karen.parsons@bookfetchinc.com", "2221 Canterbury Drive"),
("Kevin", "Carr", "kevin.carr@bookfetchinc.com", "602 Caisson Hill Road"),
("Lauren", "Mathis", "lauren.mathis@bookfetchinc.com", "2220 Canterbury Drive"),
("Lauren", "Tucker", "lauren.tucker@bookfetchinc.com", "3 West Lakeshore Drive"),
("Lily", "Randall", "lily.randall@bookfetchinc.com", "2549 Livingston Road"),
("Lucas", "Rampling", "lucas.rampling@bookfetchinc.com", "2222 Canterbury Drive"),
("Neil", "Hodges", "neil.hodges@bookfetchinc.com", "2551 Livingston Road"),
("Nicola", "Simpson", "nicola.simpson@bookfetchinc.com", "601 Caisson Hill Road"),
("Nicola", "Roberts", "nicola.roberts@bookfetchinc.com", "2223 Canterbury Drive"),
("Penelope", "Ferguson", "penelope.ferguson@bookfetchinc.com", "101 South 1st Street"),
("Peter", "Rees", "peter.rees@bookfetchinc.com", "2313 M street, NW Suite 503"),
("Peter", "Clarkson", "peter.clarkson@bookfetchinc.com", "200 Hospital Drive"),
("Phil", "Skinner", "phil.skinner@bookfetchinc.com", "2552 Livingston Road"),
("Rachel", "Ball", "rachel.ball@bookfetchinc.com", "306 Langdon Street"),
("Ruth", "North", "ruth.north@towson.edu", "8000 York Rd, Towson, MD 21252"),
("Ryan", "Robertson", "ryan.robertson@bookfetchinc.com", "1000 East 100 North"),
("Sean", "Berry", "sean.berry@bookfetchinc.com", "309 Langdon Street"),
("Stephanie", "Clarkson", "stephanie.clarkson@bookfetchinc.com", "307 Langdon Street"),
("Tracey", "Ogden", "tracey.ogden@bookfetchinc.com", "2314 M street, NW Suite 503"),
("Victor", "Hill", "victor.hill@bookfetchinc.com", "2548 Livingston Road"),
("Victoria", "Murray", "victoria.murray@umcp.edu", "College Park, MD 20742"),
("Zoe", "Sharp", "zoe.sharp@bookfetchinc.com", "2222 Canterbury Drive"),

insert into phone_number (user_id, phone_number) values
((select id from user where first_name = "James" and last_name="Tremblay"), 4155992671),
((select id from user where first_name = "Christopher" and last_name="Roy"), 4155992672),
((select id from user where first_name = "Ronald" and last_name="Gagnon"), 4155992673),
((select id from user where first_name = "Mary" and last_name="Côté"), 4155992674),
((select id from user where first_name = "Lisa" and last_name="Bouchard"), 4155992675),
((select id from user where first_name = "Michelle" and last_name="Gauthier"), 4155992676),
((select id from user where first_name = "John" and last_name="Morin"), 4155992677),
((select id from user where first_name = "Daniel" and last_name="Lavoie"), 4155992678),
((select id from user where first_name = "Anthony" and last_name="Fortin"), 4155992679),
((select id from user where first_name = "Patricia" and last_name="Gagné"), 4155992680),
((select id from user where first_name = "Nancy" and last_name="Martínez"), 4155992681),
((select id from user where first_name = "Laura" and last_name="García"), 4155992682),
((select id from user where first_name = "Robert" and last_name="Hernandez"), 4155992683),
((select id from user where first_name = "Paul" and last_name="González"), 4155992684),
((select id from user where first_name = "Kevin" and last_name="López"), 4155992685),
((select id from user where first_name = "Linda" and last_name="Rodríguez"), 4155992686),
((select id from user where first_name = "Karen" and last_name="Pérez"), 4155992687),
((select id from user where first_name = "Sarah" and last_name="Sánchez"), 4155992688),
((select id from user where first_name = "Michael" and last_name="Ramírez"), 4155992689),
((select id from user where first_name = "Mark" and last_name="Flores"), 4155992690),
((select id from user where first_name = "Mark" and last_name="Flores"), 4155992691),
((select id from user where first_name = "Mark" and last_name="Flores"), 4155992692),
((select id from user where first_name = "Michael" and last_name="Ramírez"), 4155992693),
((select id from user where first_name = "Michael" and last_name="Ramírez"), 4155992694),
((select id from user where first_name = "Michael" and last_name="Ramírez"), 4155992695),
((select id from user where first_name = "Paul" and last_name="González"), 4155992696),
((select id from user where first_name = "Paul" and last_name="González"), 4155992697),
((select id from user where first_name = "Paul" and last_name="González"), 4155992698),
((select id from user where first_name = "Paul" and last_name="González"), 4155992699),
((select id from user where first_name = "Kevin" and last_name="López"), 4155992700),
((select id from user where first_name = "Nancy" and last_name="Martínez"), 4155992702),
((select id from user where first_name = "Laura" and last_name="García"), 4155992703),
((select id from user where first_name = "Patricia" and last_name="Gagné"), 4155992704),
((select id from user where first_name = "Karen" and last_name="Pérez"), 4155992705),
((select id from user where first_name = "Linda" and last_name="Rodríguez"), 4155992706),
((select id from user where first_name = "Robert" and last_name="Hernandez"), 4155992707),
((select id from user where first_name = "Robert" and last_name="Hernandez"), 4155992708),
((select id from user where first_name = "Robert" and last_name="Hernandez"), 4155992709),
((select id from user where first_name = "Robert" and last_name="Hernandez"), 4155992701),
((select id from user where first_name = "Nancy" and last_name="Martínez"), 4155992702),
((select id from user where first_name = "John" and last_name="Morin"), 4155992677),
((select id from user where first_name = "" and last_name=""), ),
((select id from user where first_name = "" and last_name=""), ),
((select id from user where first_name = "" and last_name=""), ),
((select id from user where first_name = "Andrew" and last_name="Bower"), 7755550105),
((select id from user where first_name = "Anne" and last_name="Stewart"), 7755550130),
((select id from user where first_name = "Anthony" and last_name="Grant"), 7755550105),
((select id from user where first_name = "Austin" and last_name="Morgan"), 7755550127),
((select id from user where first_name = "Benjamin" and last_name="Vaughan"), 7755550189),
((select id from user where first_name = "Benjamin" and last_name="Dyer"), 7755550106),
((select id from user where first_name = "Boris" and last_name="McGrath"), 7755550197),
((select id from user where first_name = "Caroline" and last_name="Roberts"), 7755550143),
((select id from user where first_name = "Connor" and last_name="Black"), 7755550158),
((select id from user where first_name = "Dan" and last_name="Martin"), 7755550171),
((select id from user where first_name = "Dominic" and last_name="Lambert"), 3075550183),
((select id from user where first_name = "Donna" and last_name="Scott"), 7755550112),
((select id from user where first_name = "Heather" and last_name="Powell"), 7755550104),
((select id from user where first_name = "Jack" and last_name="Chapman"), 7755550197),
((select id from user where first_name = "Jack" and last_name="Allan"), 7755550145),
((select id from user where first_name = "James" and last_name="White"), 7755550199),
((select id from user where first_name = "James" and last_name="Bell"), 7755550196),
((select id from user where first_name = "Joan" and last_name="Lawrence"), 7755550142),
((select id from user where first_name = "Joshua" and last_name="Vaughan"), 7755550172),
((select id from user where first_name = "Joshua" and last_name="Lee"), 7755550127),
((select id from user where first_name = "Julian" and last_name="Rees"), 7755550193),
((select id from user where first_name = "Karen" and last_name="Parsons"), 7755550191),
((select id from user where first_name = "Kevin" and last_name="Carr"), 7755550172),
((select id from user where first_name = "Lauren" and last_name="Mathis"), 7755550175),
((select id from user where first_name = "Lauren" and last_name="Tucker"), 7755550152),
((select id from user where first_name = "Lily" and last_name="Randall"), 7755550192),
((select id from user where first_name = "Lucas" and last_name="Rampling"), 7755550188),
((select id from user where first_name = "Neil" and last_name="Hodges"), 7755550175),
((select id from user where first_name = "Nicola" and last_name="Simpson"), 7755550164),
((select id from user where first_name = "Nicola" and last_name="Roberts"), 7755550198),
((select id from user where first_name = "Penelope" and last_name="Ferguson"), 7755550118),
((select id from user where first_name = "Peter" and last_name="Rees"), 7755550150),
((select id from user where first_name = "Peter" and last_name="Clarkson"), 7755550167),
((select id from user where first_name = "Phil" and last_name="Skinner"), 7755550197),
((select id from user where first_name = "Rachel" and last_name="Ball"), 7755550162),
((select id from user where first_name = "Ruth" and last_name="North"), 3075550159),
((select id from user where first_name = "Ryan" and last_name="Robertson"), 7755550141),
((select id from user where first_name = "Sean" and last_name="Berry"), 7755550130),
((select id from user where first_name = "Stephanie" and last_name="Clarkson"), 7755550185),
((select id from user where first_name = "Tracey" and last_name="Ogden"), 7755550128),
((select id from user where first_name = "Victor" and last_name="Hill"), 7755550176),
((select id from user where first_name = "Victoria" and last_name="Murray"), 3075550192),
((select id from user where first_name = "Zoe" and last_name="Sharp"), 7755550172),

insert into univerity (name, repr_first_name, repr_last_name, repr_email) values
("UMBC", "Dominic", "Lambert", "dominic.lambert@umbc.edu"),
("Towson", "Ruth", "North", "ruth.north@towson.edu"),
("UMCP", "Victoria", "Murray", "victoria.murray@umcp.edu"),

insert into student (user_id, year, student_type, birthdate, university_id) values
(select id from user where first_name = "James" and last_name = "Tremblay"), 1, "UnderGrad", 1-4-1992, (select id from university where name = "Towson")),
(select id from user where first_name = "Christopher" and last_name = "Roy"), 3, "UnderGrad", 4-24-1992, (select id from university where name = "Towson")),
(select id from user where first_name = "Ronald" and last_name = "Gagnon"), 2, "UnderGrad", 6-30-1991, (select id from university where name = "Towson")),
(select id from user where first_name = "Mary" and last_name = "Côté"), 3, "UnderGrad", 9-4-1990, (select id from university where name = "Towson")),
(select id from user where first_name = "Lisa" and last_name = "Bouchard"), 4, "UnderGrad", 11-9-1989, (select id from university where name = "Towson")),
(select id from user where first_name = "Michelle" and last_name = "Gauthier"), 2, "UnderGrad", 1-14-1989, (select id from university where name = "Towson")),
(select id from user where first_name = "John" and last_name = "Morin"), 1, "UnderGrad", 3-21-1988, (select id from university where name = "Towson")),
(select id from user where first_name = "Daniel" and last_name = "Lavoie"), 4, "UnderGrad", 5-27-1987, (select id from university where name = "UMBC")),
(select id from user where first_name = "Anthony" and last_name = "Fortin"), 2, "UnderGrad", 8-1-1986, (select id from university where name = "UMBC")),
(select id from user where first_name = "Patricia" and last_name = "Gagné"), 3, "Grad", 10-6-1985, (select id from university where name = "UMBC")),
(select id from user where first_name = "Nancy" and last_name = "Martínez"), 4, "Grad", 12-11-1984, (select id from university where name = "UMBC")),
(select id from user where first_name = "Laura" and last_name = "García"), 2, "Grad", 2-16-1984, (select id from university where name = "UMBC")),
(select id from user where first_name = "Robert" and last_name = "Hernandez"), 3, "Grad", 4-23-1983, (select id from university where name = "UMBC")),
(select id from user where first_name = "Paul" and last_name = "González"), 1, "Grad", 6-28-1982, (select id from university where name = "UMBC")),
(select id from user where first_name = "Kevin" and last_name = "López"), 2, "Grad", 9-2-1981, (select id from university where name = "UMBC")),
(select id from user where first_name = "Linda" and last_name = "Rodríguez"), 3, "Grad", 11-7-1980, (select id from university where name = "UMBC")),
(select id from user where first_name = "Karen" and last_name = "Pérez"), 5, "Grad", 1-13-1980, (select id from university where name = "UMCP")),
(select id from user where first_name = "Sarah" and last_name = "Sánchez"), 2, "Grad", 3-20-1979, (select id from university where name = "UMCP")),
(select id from user where first_name = "Michael" and last_name = "Ramírez"), 4, "Grad", 5-25-1978, (select id from university where name = "UMCP")),
(select id from user where first_name = "Mark" and last_name = "Flores"), 2, "Grad", 7-30-1977, (select id from university where name = "UMCP")),
(select id from user where first_name = "Mark" and last_name = "Flores"), 2, "Grad", 7-30-1977, (select id from university where name = "UMCP")),
(select id from user where first_name = "Mark" and last_name = "Flores"), 2, "Grad", 7-30-1977, (select id from university where name = "UMCP")),
(select id from user where first_name = "Michael" and last_name = "Ramírez"), 4, "Grad", 5-25-1978, (select id from university where name = "UMCP")),
(select id from user where first_name = "Michael" and last_name = "Ramírez"), 4, "Grad", 5-25-1978, (select id from university where name = "UMCP")),
(select id from user where first_name = "Michael" and last_name = "Ramírez"), 4, "Grad", 5-25-1978, (select id from university where name = "UMCP")),
(select id from user where first_name = "Paul" and last_name = "González"), 1, "Grad", 6-28-1982, (select id from university where name = "UMBC")),
(select id from user where first_name = "Paul" and last_name = "González"), 1, "Grad", 6-28-1982, (select id from university where name = "UMBC")),
(select id from user where first_name = "Paul" and last_name = "González"), 1, "Grad", 6-28-1982, (select id from university where name = "UMBC")),
(select id from user where first_name = "Paul" and last_name = "González"), 1, "Grad", 6-28-1982, (select id from university where name = "UMBC")),
(select id from user where first_name = "Kevin" and last_name = "López"), 2, "Grad", 9-2-1981, (select id from university where name = "UMBC")),
(select id from user where first_name = "Nancy" and last_name = "Martínez"), 4, "Grad", 12-11-1984, (select id from university where name = "UMBC")),
(select id from user where first_name = "Laura" and last_name = "García"), 2, "Grad", 2-16-1984, (select id from university where name = "UMBC")),
(select id from user where first_name = "Patricia" and last_name = "Gagné"), 3, "Grad", 10-6-1985, (select id from university where name = "UMBC")),
(select id from user where first_name = "Karen" and last_name = "Pérez"), 5, "Grad", 1-13-1980, (select id from university where name = "UMCP")),
(select id from user where first_name = "Linda" and last_name = "Rodríguez"), 3, "Grad", 11-7-1980, (select id from university where name = "UMBC")),
(select id from user where first_name = "Robert" and last_name = "Hernandez"), 3, "Grad", 4-23-1983, (select id from university where name = "UMBC")),
(select id from user where first_name = "Robert" and last_name = "Hernandez"), 3, "Grad", 4-23-1983, (select id from university where name = "UMBC")),
(select id from user where first_name = "Robert" and last_name = "Hernandez"), 3, "Grad", 4-23-1983, (select id from university where name = "UMBC")),
(select id from user where first_name = "Robert" and last_name = "Hernandez"), 3, "Grad", 4-23-1983, (select id from university where name = "UMBC")),
(select id from user where first_name = "Nancy" and last_name = "Martínez"), 4, "Grad", 12-11-1984, (select id from university where name = "UMBC")),
(select id from user where first_name = "John" and last_name = "Morin"), 1, "UnderGrad", 3-21-1988, (select id from university where name = "Towson")),
(select id from user where first_name = "" and last_name = ""), , "", , (select id from university where name = "")),
(select id from user where first_name = "" and last_name = ""), , "", , (select id from university where name = "")),
(select id from user where first_name = "" and last_name = ""), , "", , (select id from university where name = "")),

insert into cart (student_id, date_created, date_updated) values
((select id from user where first_name = "James" and last_name = "Tremblay"), , ),
((select id from user where first_name = "Christopher" and last_name = "Roy"), 10/2/2014, 10/3/2014),
((select id from user where first_name = "Ronald" and last_name = "Gagnon"), 10/2/2014, 10/3/2014),
((select id from user where first_name = "Mary" and last_name = "Côté"), 10/2/2014, 10/3/2014),
((select id from user where first_name = "Lisa" and last_name = "Bouchard"), 10/3/2014, 10/4/2014),
((select id from user where first_name = "Michelle" and last_name = "Gauthier"), 10/4/2014, 10/5/2014),
((select id from user where first_name = "John" and last_name = "Morin"), , ),
((select id from user where first_name = "Daniel" and last_name = "Lavoie"), , ),
((select id from user where first_name = "Anthony" and last_name = "Fortin"), , ),
((select id from user where first_name = "Patricia" and last_name = "Gagné"), , ),
((select id from user where first_name = "Nancy" and last_name = "Martínez"), , ),
((select id from user where first_name = "Laura" and last_name = "García"), 9/8/2014, 12/15/2014),
((select id from user where first_name = "Robert" and last_name = "Hernandez"), , ),
((select id from user where first_name = "Paul" and last_name = "González"), 11/7/2014, 12/16/2014),
((select id from user where first_name = "Kevin" and last_name = "López"), , ),
((select id from user where first_name = "Linda" and last_name = "Rodríguez"), 5/1/2014, 10/14/2014),
((select id from user where first_name = "Karen" and last_name = "Pérez"), , ),
((select id from user where first_name = "Sarah" and last_name = "Sánchez"), 1/1/2014, 6/17/2014),
((select id from user where first_name = "Michael" and last_name = "Ramírez"), , ),
((select id from user where first_name = "Mark" and last_name = "Flores"), 2/1/2014, 1/2/2014),
((select id from user where first_name = "Mark" and last_name = "Flores"), , ),
((select id from user where first_name = "Mark" and last_name = "Flores"), , ),
((select id from user where first_name = "Michael" and last_name = "Ramírez"), , ),
((select id from user where first_name = "Michael" and last_name = "Ramírez"), , ),
((select id from user where first_name = "Michael" and last_name = "Ramírez"), , ),
((select id from user where first_name = "Paul" and last_name = "González"), , ),
((select id from user where first_name = "Paul" and last_name = "González"), , ),
((select id from user where first_name = "Paul" and last_name = "González"), , ),
((select id from user where first_name = "Paul" and last_name = "González"), , ),
((select id from user where first_name = "Kevin" and last_name = "López"), , ),
((select id from user where first_name = "Nancy" and last_name = "Martínez"), , ),
((select id from user where first_name = "Laura" and last_name = "García"), 1/1/2014, 3/5/2014),
((select id from user where first_name = "Patricia" and last_name = "Gagné"), 11/5/2014, 11/5/2014),
((select id from user where first_name = "Karen" and last_name = "Pérez"), 2/1/2014, 1/2/2014),
((select id from user where first_name = "Linda" and last_name = "Rodríguez"), 1/1/2014, 3/5/2014),
((select id from user where first_name = "Robert" and last_name = "Hernandez"), , ),
((select id from user where first_name = "Robert" and last_name = "Hernandez"), , ),
((select id from user where first_name = "Robert" and last_name = "Hernandez"), , ),
((select id from user where first_name = "Robert" and last_name = "Hernandez"), , ),
((select id from user where first_name = "Nancy" and last_name = "Martínez"), , ),
((select id from user where first_name = "John" and last_name = "Morin"), , ),
((select id from user where first_name = "" and last_name = ""), , ),
((select id from user where first_name = "" and last_name = ""), , ),
((select id from user where first_name = "" and last_name = ""), , ),

insert into book_order (student_id, date_created, date_fulfilled, shipping_type, cc_number, cc_expiration, cc_name, cc_type, order_status) values
((select id from user where first_name = "James" and last_name = "Tremblay"), 9-7-2014, 9-11-2014, "1-day", 4.485E+15, 3-2-2016, "card", "VISA", "shipped"),
((select id from user where first_name = "Christopher" and last_name = "Roy"), , , "", , , "", "", ""),
((select id from user where first_name = "Ronald" and last_name = "Gagnon"), , , "", , , "", "", ""),
((select id from user where first_name = "Mary" and last_name = "Côté"), , , "", , , "", "", ""),
((select id from user where first_name = "Lisa" and last_name = "Bouchard"), , , "", , , "", "", ""),
((select id from user where first_name = "Michelle" and last_name = "Gauthier"), , , "", , , "", "", ""),
((select id from user where first_name = "John" and last_name = "Morin"), , , "", , , "", "", ""),
((select id from user where first_name = "Daniel" and last_name = "Lavoie"), , , "", , , "", "", ""),
((select id from user where first_name = "Anthony" and last_name = "Fortin"), , , "", , , "", "", ""),
((select id from user where first_name = "Patricia" and last_name = "Gagné"), , , "", , , "", "", ""),
((select id from user where first_name = "Nancy" and last_name = "Martínez"), , , "", , , "", "", ""),
((select id from user where first_name = "Laura" and last_name = "García"), , , "", , , "", "", ""),
((select id from user where first_name = "Robert" and last_name = "Hernandez"), , , "", , , "", "", ""),
((select id from user where first_name = "Paul" and last_name = "González"), , , "", , , "", "", ""),
((select id from user where first_name = "Kevin" and last_name = "López"), , , "", , , "", "", ""),
((select id from user where first_name = "Linda" and last_name = "Rodríguez"), , , "", , , "", "", ""),
((select id from user where first_name = "Karen" and last_name = "Pérez"), 11-4-2014, 11-12-2014, "standard", 4.485E+15, 3-1-2016, "card", "VISA", "shipped"),
((select id from user where first_name = "Sarah" and last_name = "Sánchez"), , , "", , , "", "", ""),
((select id from user where first_name = "Michael" and last_name = "Ramírez"), 10-6-2014, , "2-day", 4.55649E+15, 5-1-2015, "plastic", "VISA", "shipping"),
((select id from user where first_name = "Mark" and last_name = "Flores"), , , "", , , "", "", ""),
((select id from user where first_name = "Mark" and last_name = "Flores"), , , "", , , "", "", ""),
((select id from user where first_name = "Mark" and last_name = "Flores"), 7-4-2014, , "standard", 4.92977E+15, 9-1-2020, "creditc", "MASTERCARD", "cancelled"),
((select id from user where first_name = "Michael" and last_name = "Ramírez"), , , "", , , "", "", ""),
((select id from user where first_name = "Michael" and last_name = "Ramírez"), , , "", , , "", "", ""),
((select id from user where first_name = "Michael" and last_name = "Ramírez"), 10-13-2014, , "1-day", 4.87868E+15, 4-1-2019, "mycard", "VISA", "new"),
((select id from user where first_name = "Paul" and last_name = "González"), 10-6-2014, 10-7-2014, "standard", 4.485E+15, 3-1-2016, "card", "VISA", "shipped"),
((select id from user where first_name = "Paul" and last_name = "González"), 9-23-2014, 9-24-2014, "1-day", 4.485E+15, 3-2-2016, "card", "VISA", "shipped"),
((select id from user where first_name = "Paul" and last_name = "González"), 10-25-2014, 10-26-2014, "1-day", 4.485E+15, 3-3-2016, "card", "VISA", "shipped"),
((select id from user where first_name = "Paul" and last_name = "González"), , , "", , , "", "", ""),
((select id from user where first_name = "Kevin" and last_name = "López"), , , "", , , "", "", ""),
((select id from user where first_name = "Nancy" and last_name = "Martínez"), , , "", , , "", "", ""),
((select id from user where first_name = "Laura" and last_name = "García"), , , "", , , "", "", ""),
((select id from user where first_name = "Patricia" and last_name = "Gagné"), , , "", , , "", "", ""),
((select id from user where first_name = "Karen" and last_name = "Pérez"), , , "", , , "", "", ""),
((select id from user where first_name = "Linda" and last_name = "Rodríguez"), , , "", , , "", "", ""),
((select id from user where first_name = "Robert" and last_name = "Hernandez"), , , "", , , "", "", ""),
((select id from user where first_name = "Robert" and last_name = "Hernandez"), , , "", , , "", "", ""),
((select id from user where first_name = "Robert" and last_name = "Hernandez"), , , "", , , "", "", ""),
((select id from user where first_name = "Robert" and last_name = "Hernandez"), , , "", , , "", "", ""),
((select id from user where first_name = "Nancy" and last_name = "Martínez"), , , "", , , "", "", ""),
((select id from user where first_name = "John" and last_name = "Morin"), , , "", , , "", "", ""),
((select id from user where first_name = "" and last_name = ""), , , "", , , "", "", ""),
((select id from user where first_name = "" and last_name = ""), , , "", , , "", "", ""),
((select id from user where first_name = "" and last_name = ""), , , "", , , "", "", ""),

insert into department (name, university_id) values
("English", (select id from university where name = "Towson")),
("English", (select id from university where name = "Towson")),
("English", (select id from university where name = "Towson")),
("English", (select id from university where name = "Towson")),
("English", (select id from university where name = "Towson")),
("English", (select id from university where name = "Towson")),
("English", (select id from university where name = "Towson")),
("English", (select id from university where name = "UMBC")),
("Computer Science", (select id from university where name = "UMBC")),
("Computer Science", (select id from university where name = "UMBC")),
("History", (select id from university where name = "UMBC")),
("History", (select id from university where name = "UMBC")),
("History", (select id from university where name = "UMBC")),
("History", (select id from university where name = "UMBC")),
("Sociology", (select id from university where name = "UMBC")),
("Sociology", (select id from university where name = "UMBC")),
("Sociology", (select id from university where name = "UMCP")),
("Sociology", (select id from university where name = "UMCP")),
("Sociology", (select id from university where name = "UMCP")),
("History", (select id from university where name = "UMCP")),
("History", (select id from university where name = "UMCP")),
("History", (select id from university where name = "UMCP")),
("Sociology", (select id from university where name = "UMCP")),
("Sociology", (select id from university where name = "UMCP")),
("Sociology", (select id from university where name = "UMCP")),
("History", (select id from university where name = "UMBC")),
("History", (select id from university where name = "UMBC")),
("History", (select id from university where name = "UMBC")),
("History", (select id from university where name = "UMBC")),
("Sociology", (select id from university where name = "UMBC")),
("History", (select id from university where name = "UMBC")),
("History", (select id from university where name = "UMBC")),
("History", (select id from university where name = "UMBC")),
("Sociology", (select id from university where name = "UMCP")),
("Sociology", (select id from university where name = "UMBC")),
("History", (select id from university where name = "UMBC")),
("History", (select id from university where name = "UMBC")),
("History", (select id from university where name = "UMBC")),
("History", (select id from university where name = "UMBC")),
("History", (select id from university where name = "UMBC")),
("English", (select id from university where name = "Towson")),
("", (select id from university where name = "")),
("", (select id from university where name = "")),
("", (select id from university where name = "")),

insert into department (name, university_id) values
("Visual Arts", (select id from university where name = "Towson")),
("Visual Arts", (select id from university where name = "UMCP")),
("Mathematics and Statistics", (select id from university where name = "Towson")),
("Mechanical Engineering", (select id from university where name = "Towson")),
("English Language Institute", (select id from university where name = "UMBC")),
("Management of Aging Services", (select id from university where name = "Towson")),
("Philosophy", (select id from university where name = "Towson")),
("Emergency Health Services", (select id from university where name = "UMBC")),
("Media and Communication Studies", (select id from university where name = "Towson")),
("Pre-Allied Health", (select id from university where name = "UMCP")),
("Music", (select id from university where name = "Towson")),
("Modern Languages, Linguistics and Intercultural Communication", (select id from university where name = "Towson")),
("Judaic Studies", (select id from university where name = "Towson")),
("Computer Science and Electrical Engineering", (select id from university where name = "UMBC")),
("English", (select id from university where name = "UMBC")),
("Economics", (select id from university where name = "UMBC")),
("Social Work", (select id from university where name = "UMCP")),
("Music", (select id from university where name = "Towson")),
("Pre-Law", (select id from university where name = "UMCP")),
("Mathematics and Statistics", (select id from university where name = "Towson")),
("Theatre", (select id from university where name = "UMCP")),
("Sociology", (select id from university where name = "UMCP")),
("Psychology", (select id from university where name = "UMCP")),
("Dance", (select id from university where name = "UMBC")),
("Mechanical Engineering", (select id from university where name = "Towson")),
("Pre-Medicine and Pre-Dentistry", (select id from university where name = "UMCP")),
("Business Technology Administration", (select id from university where name = "UMBC")),
("Chemical, Biochemical & Environmental Engineering", (select id from university where name = "UMBC")),
("Religious Studies", (select id from university where name = "UMCP")),
("Mechanical Engineering", (select id from university where name = "Towson")),
("Economics", (select id from university where name = "UMBC")),
("Education", (select id from university where name = "UMBC")),
("Chemistry and Biochemistry", (select id from university where name = "UMBC")),
("", (select id from university where name = "")),
("", (select id from university where name = "")),

insert into instructor (first_name, last_name, dept_id, university_id) values
("Julia", "Lambert", (select id from department where name = "Visual Arts"), (select id from university where name = "Towson")),
("Jessica", "Glover", (select id from department where name = "Visual Arts"), (select id from university where name = "UMCP")),
("Connor", "Edmunds", (select id from department where name = "Mathematics and Statistics"), (select id from university where name = "Towson")),
("Ian", "Gibson", (select id from department where name = "Mechanical Engineering"), (select id from university where name = "Towson")),
("Alexander", "Clarkson", (select id from department where name = "English Language Institute"), (select id from university where name = "UMBC")),
("Felicity", "Buckland", (select id from department where name = "Management of Aging Services"), (select id from university where name = "Towson")),
("Lucas", "Payne", (select id from department where name = "Philosophy"), (select id from university where name = "Towson")),
("Emma", "Kelly", (select id from department where name = "Emergency Health Services"), (select id from university where name = "UMBC")),
("Amelia", "Cameron", (select id from department where name = "Media and Communication Studies"), (select id from university where name = "Towson")),
("Isaac", "Anderson", (select id from department where name = "Pre-Allied Health"), (select id from university where name = "UMCP")),
("Una", "Oliver", (select id from department where name = "Music"), (select id from university where name = "Towson")),
("Lily", "Burgess", (select id from department where name = "Modern Languages, Linguistics and Intercultural Communication"), (select id from university where name = "Towson")),
("Piers", "Gray", (select id from department where name = "Judaic Studies"), (select id from university where name = "Towson")),
("Harry", "Mills", (select id from department where name = "Computer Science and Electrical Engineering"), (select id from university where name = "UMBC")),
("Fiona", "Hamilton", (select id from department where name = "English"), (select id from university where name = "UMBC")),
("Yvonne", "Wilkins", (select id from department where name = "Economics"), (select id from university where name = "UMBC")),
("Piers", "Peters", (select id from department where name = "Social Work"), (select id from university where name = "UMCP")),
("Una", "Oliver", (select id from department where name = "Music"), (select id from university where name = "Towson")),
("Hannah", "Bond", (select id from department where name = "Pre-Law"), (select id from university where name = "UMCP")),
("Connor", "Edmunds", (select id from department where name = "Mathematics and Statistics"), (select id from university where name = "Towson")),
("Mary", "Ogden", (select id from department where name = "Theatre"), (select id from university where name = "UMCP")),
("Richard", "Clark", (select id from department where name = "Sociology"), (select id from university where name = "UMCP")),
("Colin", "Nolan", (select id from department where name = "Psychology"), (select id from university where name = "UMCP")),
("Sean", "Lee", (select id from department where name = "Dance"), (select id from university where name = "UMBC")),
("Ian", "Gibson", (select id from department where name = "Mechanical Engineering"), (select id from university where name = "Towson")),
("Leonard", "Wilkins", (select id from department where name = "Pre-Medicine and Pre-Dentistry"), (select id from university where name = "UMCP")),
("Stephen", "Manning", (select id from department where name = "Business Technology Administration"), (select id from university where name = "UMBC")),
("Jake", "Jackson", (select id from department where name = "Chemical, Biochemical & Environmental Engineering"), (select id from university where name = "UMBC")),
("Amanda", "Blake", (select id from department where name = "Religious Studies"), (select id from university where name = "UMCP")),
("Ian", "Gibson", (select id from department where name = "Mechanical Engineering"), (select id from university where name = "Towson")),
("Yvonne", "Wilkins", (select id from department where name = "Economics"), (select id from university where name = "UMBC")),
("Justin", "Turner", (select id from department where name = "Education"), (select id from university where name = "UMBC")),
("Brian", "Lambert", (select id from department where name = "Chemistry and Biochemistry"), (select id from university where name = "UMBC")),
("", "", (select id from department where name = ""), (select id from university where name = "")),
("", "", (select id from department where name = ""), (select id from university where name = "")),

